My\TestBundle\Entity\GuitarSpec:
    type: entity
    table: null
    repositoryClass: My\TestBundle\Entity\GuitarSpecRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        builder:
            type: string
            length: 255
        model:
            type: string
            length: 255
        type:
            type: string
            length: 255
        backWood:
            type: string
            length: 255
            column: back_wood
        topWood:
            type: string
            length: 255
            column: top_wood
    lifecycleCallbacks: {  }
