<?php

namespace My\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuitarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuitarRepository extends EntityRepository
{
}
