<?php

namespace My\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuitarSpecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuitarSpecRepository extends EntityRepository
{
}
